version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: test-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: testdb
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpass
    volumes:
      - mongo_data:/data/db
    networks:
      - testnet

volumes:
  mongo_data:

networks:
  testnet:
