spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  # Database Properties
  data:
    mongodb:
      authentication-database: admin
      #uri: ${DATABASE_URL}
      #      uri: mongodb://admin:admin@localhost:27017/objectStorageDB?authSource=admin
      uri: mongodb://admin:admin@192.168.42.140:27017/objectStorageDB?authSource=admin
      auto-index-creation: true
  banner:
    charset: UTF-8
  # Multipart Properties
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            repository:
              query: DEBUG
server:
  port: 8080



